### ISSUE TITLE
Possibility to Control PV SmartGrid

### ISSUE THREAD

**Issue by g4challenge** [mbuchber/ha_heliotherm#11]
In the Heliotherm Heatpump there is a set of holding registers in modbus (117 e.g.) which can be used to automate PV Production with other tools like https://github.com/InventoCasa/ha-advanced-blueprints/tree/main/PV_Excess_Control - this could be immensly helpful.

Otherwise your integration worked flawlessly with modbus via tcp and latest Homeassistant 2023.06

**Comment by mbuchber** [comment]
As far as I know, these modbus registers just store the destination device (i.e. inverter) as destination device for PV ready control. What would be the benefit for using these registers from HASS?

**Comment by g4challenge** [comment]
I think you can do more, e.g. register 117: is UINT16 and contains "PV Anforderung 0 oder 1". The following registers are offsets for temperatures in cooling.
