### ISSUE TITLE
Update to v1.0.2 changes of orders of magnitude

### ISSUE THREAD

**Issue by Johndowne** [mbuchber/ha_heliotherm#23]
I installed this update yesterday and it seems to have significantly changed the order of magnitude of the cumulative kWh electricity consumed which has increased from about 500 to 10,000 using this sensor…
sensor.heliotherm_heatpump_stromzahler_gesamt

and the cumulative kWh of heat output has decreased from around 22,000 to 6,000 using this sensor…
sensor.heliotherm_heatpump_wmz_heizung

Both sensors are now increasing at much higher rates.

Has the precision of these readings increased so that there should be decimal places rather than just integers maybe?

**Comment by Johndowne** [comment]
I have a Heliotherm 8kW ASHP by the way.

**Comment by mbuchber** [comment]
Can you check the current version again please?

**Comment by Johndowne** [comment]
Apologies, but how do I check that?

**Comment by Johndowne** [comment]
With .23 the energy in and energy out figures are back in the ranges they were in before! So that is a result thank you (except for some crazy data so far today but I can live with that).
Thanks for resolving and your very useful Heliotherm integration.
