### ISSUE TITLE
WMZ Brauchwasser shows negative energy statistics

### ISSUE THREAD

**Issue by pbleij** [mbuchber/ha_heliotherm#24]
Since January 17th  the WMZ sensors/measurements are showing negative values. Then they grow to positive again and rest to a very negative value.
I think Jan 17th was the time I updated the custom integration but not exactly sure. 
I attached screenshot of what is seen.

![Screenshot_20240123-202021](https://github.com/mbuchber/ha_heliotherm/assets/113504309/d52204ef-25de-40f4-9c72-a7c710a564ad)
![Screenshot_20240123-200659](https://github.com/mbuchber/ha_heliotherm/assets/113504309/a1620938-1732-4ba6-bbbe-00d0dbac5b4d)

**Comment by drahdiwaberl** [comment]
so your heatpump produces 85000 kWh heat per week? heating Schloss Schönbrunn? ;)

did this recover at some point or is it still acting that way?

**Comment by pbleij** [comment]
Hi mbuchber,

😁 Nope. Not at all. Per day around 7,5kWh heat for a 300l boiler (around 1,5kWh electrical energy per day)..
I saw these thermic statstics moving up and down with unrealistic big amounts.

But I do realize now that I should have checked the Heliotherm internal statistics first. But as it reset regular to a minus amount of kWh I thought it was the reading and graphs of HA.

I'm remote now so cannot check comparison between HA en Heliotherm as my HA is only available within my router network.

Also it is given a hard reset to I think factory settings so since aohth every single history is gone.

Will check when coming back home next week.
But of nothing an be seen I think we rather close this one.

Tha kan again by the way for fixing this thermostat in the heliotherm integration a few months ago 🙏

Regards,
Pascal

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
